[
  {
    RuleShowType: 0,
    RuleName: '商场补贴',
    IsShow: false,
    Status: true,
    ShowType: 0,
    SelectedMaxCount: 0,
    RightsList: [],
    Checked: false,
    NeedMany: 0,
    DiscountType: 0,
    IsZeroLimit: false,
    ZeroType: 0,
    ZeroParams: '',
    IsIntellegent: false,
    IntellegentType: 0,
    IntellegentParams: ''
  },
  {
    RuleShowType: 0,
    RuleName: '会员权益',
    IsShow: false,
    Status: true,
    ShowType: 0,
    SelectedMaxCount: 0,
    RightsList: [],
    Checked: false,
    NeedMany: 0,
    DiscountType: 0,
    IsZeroLimit: false,
    ZeroType: 0,
    ZeroParams: '',
    IsIntellegent: false,
    IntellegentType: 0,
    IntellegentParams: ''
  },
  {
    RuleShowType: 0,
    RuleName: '付费会员权益',
    IsShow: false,
    Status: true,
    ShowType: 0,
    SelectedMaxCount: 0,
    RightsList: [],
    Checked: false,
    NeedMany: 0,
    DiscountType: 0,
    IsZeroLimit: false,
    ZeroType: 0,
    ZeroParams: '',
    IsIntellegent: false,
    IntellegentType: 0,
    IntellegentParams: ''
  },
  {
    RuleShowType: 0,
    RuleName: '商场停车券',
    IsShow: false,
    Status: true,
    ShowType: 0,
    SelectedMaxCount: 0,
    RightsList: [],
    Checked: false,
    NeedMany: 0,
    DiscountType: 0,
    IsZeroLimit: false,
    ZeroType: 0,
    ZeroParams: '',
    IsIntellegent: false,
    IntellegentType: 0,
    IntellegentParams: ''
  },
  {
    RuleShowType: 0,
    RuleName: '商场积分',
    IsShow: false,
    Status: true,
    ShowType: 0,
    SelectedMaxCount: 0,
    RightsList: [],
    Checked: false,
    NeedMany: 0,
    DiscountType: 0,
    IsZeroLimit: false,
    ZeroType: 0,
    ZeroParams: '',
    IsIntellegent: false,
    IntellegentType: 0,
    IntellegentParams: ''
  }
]